version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-network
    environment:
      - keyvault_name=${keyvault_name}
      - cosmosdb_account_name=${cosmosdb_account_name}
      - azure_client_id=${azure_client_id}
      - azure_tenant_id=${azure_tenant_id}
      - azure_client_secret=${azure_client_secret}
      - cosmos_connection_string=${cosmos_connection_string}
    restart: unless-stopped
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge
