# backend/course_types.py

# List of courses to manage dynamically
COURSE_TYPES = [
    # college of business = 15
    {"level": "bachelor", "course_type": "accountancy"},
    {"level": "bachelor", "course_type": "business_analytics"},
    {"level": "bachelor", "course_type": "economics_minor"},
    {"level": "bachelor", "course_type": "economics_finance_double_major"},
    {"level": "bachelor", "course_type": "economics"},
    {"level": "bachelor", "course_type": "entrepreneurship_innovation"},
    {"level": "bachelor", "course_type": "finance"},
    {"level": "bachelor", "course_type": "global_supply_chain_management"},
    {"level": "bachelor", "course_type": "hospitality_tourism_management_event_and_destination_management"},
    {"level": "bachelor", "course_type": "hospitality_tourism_management_lodging_asset_ownership_and_management"},
    {"level": "bachelor", "course_type": "hospitality_tourism_management_restaurant_entrepreneurship_and_management"},
    {"level": "bachelor", "course_type": "information_systems"},
    {"level": "bachelor", "course_type": "international_business"},
    {"level": "bachelor", "course_type": "management"},
    {"level": "bachelor", "course_type": "marketing"},

    # college of education = 5
    {"level": "bachelor", "course_type": "early_care_early_childhood_studies"},
    {"level": "bachelor", "course_type": "early_care_early_childhood_studies_teacher_certification"},
    {"level": "bachelor", "course_type": "education_bilingual_education_ec_sixth_certification"},
    {"level": "bachelor", "course_type": "education_english_as_a_second_language_ec_sixth_certification"},
    {"level": "bachelor", "course_type": "education_special_education"},

    # college of engineering = 8
    {"level": "bachelor", "course_type": "civil_engineering"},
    {"level": "bachelor", "course_type": "computer_engineering"},
    {"level": "bachelor", "course_type": "computer_science"},
    {"level": "bachelor", "course_type": "cyber_security"},
    {"level": "bachelor", "course_type": "electrical_engineering"},
    {"level": "bachelor", "course_type": "manufacturing_engineering"},
    {"level": "bachelor", "course_type": "mechanical_engineering"},
    {"level": "bachelor", "course_type": "engineering_technology"},

    # college of fine arts = 27
    {"level": "bachelor", "course_type": "art_all_level_secondary_education_minor"},
    {"level": "bachelor", "course_type": "art_ceramics"},
    {"level": "bachelor", "course_type": "art_sculpture"},
    {"level": "bachelor", "course_type": "art_studio_art"},
    {"level": "bachelor", "course_type": "art_teacher_certification"},
    {"level": "bachelor", "course_type": "fine_art_dance_mexican_dance"},
    {"level": "bachelor", "course_type": "art_dance_teacher_certification"},
    {"level": "bachelor", "course_type": "art_dance"},
    {"level": "bachelor", "course_type": "fine_art_dance"},
    {"level": "bachelor", "course_type": "music_guitar_teacher_certification"},
    {"level": "bachelor", "course_type": "music_mariachi_teacher_certification"},
    {"level": "bachelor", "course_type": "piano_teacher_certification"},
    {"level": "bachelor", "course_type": "music_string_teacher_certification"},
    {"level": "bachelor", "course_type": "music_voice_teacher_certification"},
    {"level": "bachelor", "course_type": "woodwinds_brass_percussion_teacher_certification"},
    {"level": "bachelor", "course_type": "music_music_composition"},
    {"level": "bachelor", "course_type": "music_music_technology"},
    {"level": "bachelor", "course_type": "performance_guitar"},
    {"level": "bachelor", "course_type": "performance_piano"},
    {"level": "bachelor", "course_type": "performance_string"},
    {"level": "bachelor", "course_type": "performance_voice"},
    {"level": "bachelor", "course_type": "performance_woodwinds_brass_percussion"},
    {"level": "bachelor", "course_type": "theatre_design_technical"},
    {"level": "bachelor", "course_type": "theatre_film_production"},
    {"level": "bachelor", "course_type": "theatre_performance"},
    {"level": "bachelor", "course_type": "theatre_teacher_certification"},
    {"level": "bachelor", "course_type": "visual_communication_design"},

    # college of health professions = 25
    {"level": "bachelor", "course_type": "addiction_studies"},
    {"level": "bachelor", "course_type": "american_sign_language_interpretation_communication_studies"},
    {"level": "bachelor", "course_type": "american_sign_language_interpretation_spanish_translation_and_interpreting"},
    {"level": "bachelor", "course_type": "biomedical_science"},
    {"level": "bachelor", "course_type": "communication_sciences_audiology_american_sign_language"},
    {"level": "bachelor", "course_type": "communication_sciences_speech_language_pathology_american_sign_language"},
    {"level": "bachelor", "course_type": "exercise_science_occupational_therapy"},
    {"level": "bachelor", "course_type": "exercise_science_physical_therapy"},
    {"level": "bachelor", "course_type": "exercise_science"},
    {"level": "bachelor", "course_type": "health_services_technology"},
    {"level": "bachelor", "course_type": "health"},
    {"level": "bachelor", "course_type": "integrated_health_science_clinical_professions"},
    {"level": "bachelor", "course_type": "integrated_health_science_health_services"},
    {"level": "bachelor", "course_type": "integrated_health_science_professional_studies"},
    {"level": "bachelor", "course_type": "kinesiology_athletic_training"},
    {"level": "bachelor", "course_type": "kinesiology_coaching"},
    {"level": "bachelor", "course_type": "kinesiology_recreational_sports_management"},
    {"level": "bachelor", "course_type": "kinesiology_teacher_certification"},
    {"level": "bachelor", "course_type": "kinesiology"},
    {"level": "bachelor", "course_type": "medical_laboratory_science"},
    {"level": "bachelor", "course_type": "nutritional_sciences_nutrition"},
    {"level": "bachelor", "course_type": "nutritional_sciences_food_and_technology_management"},
    {"level": "bachelor", "course_type": "nutritional_sciences_nutrition_and_fitness"},
    {"level": "bachelor", "course_type": "rehabilitation_services_deaf_and_hard_of_hearing"},
    {"level": "bachelor", "course_type": "rehabilitation_services"},

    # college of liberal arts = 30
    {"level": "bachelor", "course_type": "anthropology_archaeology"},
    {"level": "bachelor", "course_type": "anthropology_global_health_and_migration"},
    {"level": "bachelor", "course_type": "anthropology"},
    {"level": "bachelor", "course_type": "criminal_justice"},
    {"level": "bachelor", "course_type": "communication_studies"},
    {"level": "bachelor", "course_type": "english_rhetoric_composition_literacy_studies"},
    {"level": "bachelor", "course_type": "english_creative_writing"},
    {"level": "bachelor", "course_type": "english_teacher_certification_seventh_twelfth"},
    {"level": "bachelor", "course_type": "english_language_arts"},
    {"level": "bachelor", "course_type": "history"},
    {"level": "bachelor", "course_type": "history_teacher_certification"},
    {"level": "bachelor", "course_type": "human_dimensions_organizations"},
    {"level": "bachelor", "course_type": "mass_communication_advertising_and_public_relations"},
    {"level": "bachelor", "course_type": "mass_communication_broadcast"},
    {"level": "bachelor", "course_type": "mass_communication_print_journalism"},
    {"level": "bachelor", "course_type": "medical_and_health_humanities"},
    {"level": "bachelor", "course_type": "mexican_american_studies"},
    {"level": "bachelor", "course_type": "multidisciplinary_studies"},
    {"level": "bachelor", "course_type": "philosophy_pre_law"},
    {"level": "bachelor", "course_type": "philosophy"},
    {"level": "bachelor", "course_type": "public_heritage_community_engagement_bilingual_bicultural_border_heritage"},
    {"level": "bachelor", "course_type": "public_heritage_community_engagement_cultural_and_natural_landscapes"},
    {"level": "bachelor", "course_type": "psychology"},
    {"level": "bachelor", "course_type": "political_science"},
    {"level": "bachelor", "course_type": "social_studies_composite"},
    {"level": "bachelor", "course_type": "social_studies_composite_teacher_certification"},
    {"level": "bachelor", "course_type": "sociology"},
    {"level": "bachelor", "course_type": "spanish"},
    {"level": "bachelor", "course_type": "spanish_teacher_certification"},
    {"level": "bachelor", "course_type": "spanish_translation_interpreting"},

    # college of sciences = 25
    {"level": "bachelor", "course_type": "applied_statistics_data_science"},
    {"level": "bachelor", "course_type": "biology"},
    {"level": "bachelor", "course_type": "biology_seventh_twelfth_teacher_certification"},
    {"level": "bachelor", "course_type": "chemistry"},
    {"level": "bachelor", "course_type": "chemistry_seventh_twelfth_teacher_certification"},
    {"level": "bachelor", "course_type": "environmental_science_earth_and_ocean_sciences"},
    {"level": "bachelor", "course_type": "environmental_science_environment_and_society"},
    {"level": "bachelor", "course_type": "environmental_science_environmental_biology"},
    {"level": "bachelor", "course_type": "environmental_science_environmental_chemistry"},
    {"level": "bachelor", "course_type": "environmental_science_interdisciplinary_environmental_science"},
    {"level": "bachelor", "course_type": "interdisciplinary_studies_middle_school_mathematics_fourth_eight_teacher_certification"},
    {"level": "bachelor", "course_type": "interdisciplinary_studies_science_fourth_eight_teacher_certification"},
    {"level": "bachelor", "course_type": "marine_biology"},
    {"level": "bachelor", "course_type": "mathematics_fourth_eight_teacher_certification"},
    {"level": "bachelor", "course_type": "mathematics_seventh_twelfth_teacher_certification"},
    {"level": "bachelor", "course_type": "mathematics_applied_mathematics"},
    {"level": "bachelor", "course_type": "mathematics_economics"},
    {"level": "bachelor", "course_type": "mathematics_pure_math"},
    {"level": "bachelor", "course_type": "mathematics_science_and_engineering"},
    {"level": "bachelor", "course_type": "mathematics_statistics"},
    {"level": "bachelor", "course_type": "physics_biophysics"},
    {"level": "bachelor", "course_type": "physics_minor_required"},
    {"level": "bachelor", "course_type": "physics_pure_and_applied_physics"},
    {"level": "bachelor", "course_type": "physics_teacher_certification"},
    {"level": "bachelor", "course_type": "sustainable_agriculture_food_systems"},

    # school of nursing = 3
    {"level": "bachelor", "course_type": "nursing_rn_to_bsn"},
    {"level": "bachelor", "course_type": "nursing_second_degree"},
    {"level": "bachelor", "course_type": "nursing"},

    # school of social work = 1
    {"level": "bachelor", "course_type": "social_work"},
]
